### ISSUE TITLE
Issue when using vite4

### ISSUE THREAD

**Issue by sourcenux** [vitejs/vite-plugin-basic-ssl#15]
Hi,

I am using the below pasted vite.config.js for vite. When adding "basicSsl()" as Plugin vite does not respond to requests anymore. It causes 100% cpu load (single threaded) and can not be stopped besides killing it forcefully. Everything works fine, if basicssl is disabled and vite is being used via http. My Application is using VueJS 3.2.26. I've added my package.json further below.

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import basicSsl from '@vitejs/plugin-basic-ssl'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()
,basicSsl()
],
  server: {
        host: true,
        port: '8080',

        }

})

```
```

  "name": "hausverwaltung-client",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "@vitejs/plugin-basic-ssl": "^1.0.1",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vuepic/vue-datepicker": "^3.2.0",
    "axios": "^0.21.4",
    "serve": "^14.1.2",
    "vue": "^3.2.26",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.2.26",
    "vite": "^4.0.0"
  }
}
```

**Comment by danielgek** [comment]
@sourcenux i'm ahing the same problem either with this or with certificates generated by me, did you get around the issue some how ?

**Comment by bluwy** [comment]
Is this still happening in Vite 5?

**Comment by patak-dev** [comment]
Let's close this one, please create a new issue against Vite 5 if there is still a problem
