### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by eighty4** [vitejs/vite-plugin-basic-ssl#18]
I'm new to vite by way of sveltekit and I'm curious if this plugin could redirect http requests to https? I'm not familiar with vite's plugin APIs and how much extensibility and control there is. Would config like this be possible to listen for http and redirect to https?

```
import ssl from '@vitejs/plugin-basic-ssl'
ssl({redirectHttp: true})
```

Would be very helpful. Happy to investigate further and attempt a PR.

**Comment by patak-dev** [comment]
This plugin is only intended to auto-create certificates. We intend to keep the current scope.
For reference, we removed this plugin from core because we think users should create their own certificates.

**Comment by eighty4** [comment]
Sure, I figured this plugin was really only usable for a local dev setup, where the redirect http to https seemed like a useful simplicity for developing
