### ISSUE TITLE
Can not start dev server on vite 4.3 beta

### ISSUE THREAD

**Issue by cnguyen-de** [vitejs/vite-plugin-basic-ssl#19]
I use vite-plugin-basic-ssl to use https on local server but it sadly doesn't seem to work with latest Vite 4.3 beta 4 (also didn't work with beta 2 when I checked out earlier last week).

When running vite serve, i got the following message:

```
Starting in development mode...
error when starting dev server:
Error: ENAMETOOLONG: name too long, open '/Users/...-----BEGIN RSA PRIVATE KEY-----
....
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
'
 ELIFECYCLE  Command failed with exit code 1.
```

I assume that this plugin isn't yet compatible with newest vite?

**Comment by patak-dev** [comment]
It should be fixed in vite@4.3.0-beta.5, thanks for the report
