### ISSUE TITLE
"This expression is not callable." when using TypeScript with `moduleResolution` set to  `node16` or `nodenext`

### ISSUE THREAD

**Issue by wojtekmaj** [vitejs/vite-plugin-basic-ssl#24]
When @vitejs/plugin-basic-ssl is used in a project with moduleResolution: nodenext, the following error appears:

```
vite.config.ts:166:5 - error TS2349: This expression is not callable.
  Type 'typeof import("/node_modules/@vitejs/plugin-basic-ssl/dist/index")' has no call signatures.

166     basicSslPlugin(),
        ~~~~~~~~~~~~~~
```

Quick check at arethetypeswrong confirms that types are indeed wrongly configured for ESM projects: https://arethetypeswrong.github.io/?p=%40vitejs%2Fplugin-basic-ssl%401.1.0

To fix that, my suggestion is to:

- Ensure each version of the plugin has its own declaration file.
    Current state:
    ```
    dist
      index.cjs
      index.d.ts <-- not a sibling of any JS file
      index.mjs <-- missing declarations
    ```
    Desired state:
    ```
    dist
      index.cjs
      index.d.cts <-- declarations for .cjs file
      index.mjs
      index.d.mts <-- declarations for .mjs file
    ```
- Remove `types` and `exports["."].types` from package.json, as since every JS file would have a corresponding sibling declaration file, these would be redundant or even misleading.

Site note: could also add "type": "module" and change .mjs/.d.mts extensions to .js/.d.ts respectively while at it.

**Comment by evertdespiegeleer** [comment]
A bit ugly for sure, but a workaround:

```ts
import { defineConfig, loadEnv } from 'vite'
import basicSsl from '@vitejs/plugin-basic-ssl'

export default defineConfig(({ mode }) => {
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }
  return defineConfig({
    plugins: [
      // ⬇️
      basicSsl.default()
    ],
  })
}
)

```
