### ISSUE TITLE
cacheDir path is missing the root path

### ISSUE THREAD

**Issue by cedeber** [vitejs/vite-plugin-basic-ssl#3]
Hello. Looks like the `cacheDir` option in Vite config file is broken. I feel like the `root` option has been forgotten.
```js
{
  root: "./packages/application",
  cacheDir: ".cache"
}
```
It does save the certificate into `/.cache` instead of `./packages/application/.cache`.
Thanks.

**Comment by PengBoUESTC** [comment]
> Hello. Looks like the `cacheDir` option in Vite config file is broken. I feel like the `root` option has been forgotten.
> 
> ```js
> {
>   root: "./packages/application",
>   cacheDir: ".cache"
> }
> ```
> 
> It does save the certificate into `/.cache` instead of `./packages/application/.cache`. Thanks.
 this plugin compute cacheDir itself  which is different from the rule of `vite`, I think the hook used in this plugin is a little `early`
