### ISSUE TITLE
Incompatible with Vite 4.X.

### ISSUE THREAD

**Issue by okydk** [vitejs/vite-plugin-basic-ssl#7]
Peer dependency should be upgraded to Vite 4.
```
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.0.0-beta.0" from @vitejs/plugin-basic-ssl@0.1.2
npm ERR! node_modules/@vitejs/plugin-basic-ssl
npm ERR!   dev @vitejs/plugin-basic-ssl@"^0.1.2" from the root project
```

**Comment by patak-dev** [comment]
thanks for the heads up! Fixed in https://github.com/vitejs/vite-plugin-basic-ssl/pull/8 and released as 1.0

**Comment by phillip-haydon** [comment]
@patak-dev unsure its working, just upgraded and now I'm getting `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

Tried creating a new clean site and got the same error. (chrome, firefox, and in remote chrome/firefox)

**Comment by phillip-haydon** [comment]
@patak-dev 1.0.1 is working again! Thanks @hugoattal it appears your fix worked! ❤️
