### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by geekact** [vitejs/vite-plugin-basic-ssl#9]
Add options to configure where needs ssl, for example:
```typescript
ssl({
  server: true,
  preview: true,
});
```

Or just checking config
```typescript
const https = { cert: '', key: '' };

if (config?.server.https === true) {
 // assign https
}
if (config?.preview.https === true) {
  // assign https
}
```

**Comment by sand4rt** [comment]
Library authors can't check if https is set when `config?.server.https` or `config?.preview.https` is not specified right?

**Comment by geekact** [comment]
> Library authors can't check if https is set when `config?.server.https` or `config?.preview.https` is not specified right? Would specify it instead like:
> 
> ```ts
> export default defineConfig({
>   plugins: [basicSsl()],
>   server: {
>     https: true
>   },
>   preview: {
>     https: true
>   }
> });
> ```

You are providing a new way and it just up to maintainers.

**Comment by sand4rt** [comment]
Yeah it's up to the maintainers i'm just sharing some thoughts here :) It's not really a new way or do i miss something?: [preview.https](https://vitejs.dev/config/server-options.html#preview-https)
type: `boolean | https.ServerOptions`

**Comment by digiinsanity** [comment]
Being able to set the proposed options or for the plugin to respect the user defined settings would be beneficial.
To address the issue, i created PR #16.

**Comment by bluwy** [comment]
This is fixed in https://github.com/vitejs/vite-plugin-basic-ssl/pull/16
